name: Docker Image CI Linux ghcr.io

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.actor }}/pyinstaller-linux

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: v2.2.4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push slim bookworm Docker image
        id: build-slim-bookworm-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile-py3-linux-slim
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.12.5-slim-bookworm
          tags: |
            ${{ steps.meta.outputs.tags }}-slim
            ${{ steps.meta.outputs.tags }}-slim-bookworm
          labels: |
            ${{ steps.meta.outputs.labels }}-slim
            ${{ steps.meta.outputs.labels }}-slim-bookworm
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push slim bullseye Docker image
        id: build-slim-bullseye-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile-py3-linux-slim
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.12.5-slim-bullseye
          tags: |
            ${{ steps.meta.outputs.tags }}-slim-bullseye
          labels: |
            ${{ steps.meta.outputs.labels }}-slim-bullseye
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push bookworm Docker image
        id: build-bookworm-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile-py3-linux
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.12.5-bookworm
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta.outputs.tags }}-bookworm
          labels: |
            ${{ steps.meta.outputs.labels }}
            ${{ steps.meta.outputs.labels }}-bookworm
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push bullseye Docker image
        id: build-bullseye-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile-py3-linux
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.12.5-bullseye
          tags: |
            ${{ steps.meta.outputs.tags }}-bullseye
          labels: |
            ${{ steps.meta.outputs.labels }}-bullseye
          cache-from: type=gha
          cache-to: type=gha,mode=max
